global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scheme: https
    basic_auth:
      username: 'user'
      password: 'password'
    tls_config:
      ca_file: /etc/prometheus/cert.pem
      # insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8443']
